// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTrack struct {
	Name   string `json:"name"`
	Artist string `json:"artist"`
	Album  string `json:"album"`
}

type Tracks struct {
	Name   string `json:"name"`
	Artist string `json:"artist"`
	Album  string `json:"album"`
}
